export const iconMap = {
  SettingsIcon: "settings-rounded",
  CompressIcon: "compress-rounded",
  SwapHorizIcon: "swap-horiz-rounded",
  CleaningServicesIcon: "cleaning-services-rounded",
  CropIcon: "crop-rounded",
  TextFieldsIcon: "text-fields-rounded",
  PictureAsPdfIcon: "picture-as-pdf-rounded",
  EditIcon: "edit-rounded",
  DeleteIcon: "delete-rounded",
  FolderIcon: "folder-rounded",
  CloudIcon: "cloud-rounded",
  StorageIcon: "storage-rounded",
  SearchIcon: "search-rounded",
  DownloadIcon: "download-rounded",
  UploadIcon: "upload-rounded",
  PlayArrowIcon: "play-arrow-rounded",
  RotateLeftIcon: "rotate-left-rounded",
  RotateRightIcon: "rotate-right-rounded",
  VisibilityIcon: "visibility-rounded",
  ContentCutIcon: "content-cut-rounded",
  ContentCopyIcon: "content-copy-rounded",
  WorkIcon: "work-rounded",
  BuildIcon: "build-rounded",
  AutoAwesomeIcon: "auto-awesome-rounded",
  SmartToyIcon: "smart-toy-rounded",
  CheckIcon: "check-rounded",
  SecurityIcon: "security-rounded",
  StarIcon: "star-rounded",
};

export const iconOptions = [
  { value: "SettingsIcon", label: "Settings" },
  { value: "CompressIcon", label: "Compress" },
  { value: "SwapHorizIcon", label: "Convert" },
  { value: "CleaningServicesIcon", label: "Clean" },
  { value: "CropIcon", label: "Crop" },
  { value: "TextFieldsIcon", label: "Text" },
  { value: "PictureAsPdfIcon", label: "PDF" },
  { value: "EditIcon", label: "Edit" },
  { value: "DeleteIcon", label: "Delete" },
  { value: "FolderIcon", label: "Folder" },
  { value: "CloudIcon", label: "Cloud" },
  { value: "StorageIcon", label: "Storage" },
  { value: "SearchIcon", label: "Search" },
  { value: "DownloadIcon", label: "Download" },
  { value: "UploadIcon", label: "Upload" },
  { value: "PlayArrowIcon", label: "Play" },
  { value: "RotateLeftIcon", label: "Rotate Left" },
  { value: "RotateRightIcon", label: "Rotate Right" },
  { value: "VisibilityIcon", label: "View" },
  { value: "ContentCutIcon", label: "Cut" },
  { value: "ContentCopyIcon", label: "Copy" },
  { value: "WorkIcon", label: "Work" },
  { value: "BuildIcon", label: "Build" },
  { value: "AutoAwesomeIcon", label: "Magic" },
  { value: "SmartToyIcon", label: "Robot" },
  { value: "CheckIcon", label: "Check" },
  { value: "SecurityIcon", label: "Security" },
  { value: "StarIcon", label: "Star" },
];

export type IconKey = keyof typeof iconMap;
